import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-5xl mx-auto p-4">
          <header className="flex items-center justify-between py-4">
            <a className="font-semibold" href="/">Next.js Scheduler</a>
            <nav className="flex gap-3 text-sm">
              <a href="/buyer">Buyer</a>
              <a href="/dashboard">Seller</a>
              <a href="/appointments">Appointments</a>
              <a href="/api/auth/signin">Sign in</a>
              <a href="/api/auth/signout">Sign out</a>
            </nav>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
